<?php

$r_lnums = array(
	"0",
	"-1",
	"4294967295",
	"2147483647",
	"-2147483648",
	"\"inf\"",
);

$r_dnums = array(
	"0.0",
	"-1.0"
);

$r_exponent_dnums = array(
	"2.2250738585072011e-308",
);

$r_hnums = array(
	"0x00000000",
	"0x7fffffff",
	"0x80000000",
	"0xffffffff",
);

$r_bnums = array(
	"0b00000000",
	"0b01111111",
	"0b10000000",
	"0b11111111",
);

$r_labels = array(
	"label1:",
	"label2:",
	"label3:",
);

$r_strings = array(
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ",
	"%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n ",
	"AAAAAAAAAA ",
	"%n%n%n%n%n%n%n%n%n%n ",
	"string1 ",
	"string2 ",
	"string3 ",
	"string4 ",
	"string5 ",
    "abstract ",
    "and ",
    "array ",
    "as ",
    "break ",
    "callable ",
    "case ",
    "catch ",
    "class ",
    "clone ",
    "const ",
    "continue ",
    "declare ",
    "default ",
    "do ",
    "echo ",
    "else ",
    "elseif ",
    "empty ",
    "enddeclare ",
    "endfor ",
    "endforeach ",
    "endif ",
    "endswitch ",
    "endwhile ",
    "eval ",
    "extends ",
    "final ",
    "finally ",
    "for ",
    "foreach ",
    "function ",
    "global ",
    "goto ",
    "if ",
    "implements ",
    "include ",
    "include_once ",
    "instanceof ",
    "insteadof ",
    "interface ",
    "isset ",
    "list ",
    "namespace ",
    "new ",
    "or ",
    "print ",
    "private ",
    "protected ",
    "public ",
    "require ",
    "require_once ",
    "return ",
    "static ",
    "switch ",
    "throw ",
    "trait ",
    "try ",
    "unset ",
    "use ",
    "var ",
    "xor ",
    "yield ",
    "int ",
    "float ",
    "bool ",
    "string ",
    "true ",
    "false ",
    "null ",
    "resource ",
    "object ",
    "mixed ",
    "numeric ",
    "is_set ",
    "unset ",
    "printf ",
    "unserialize ",
    "serialize ",
    "range ",
    "round ",
    "rand ",
    "strpos ",
    "str_repeat ",
    "preg_match ",
    "fopen ",
    "fwrite ",
    "fread ",
    "fclose ",
    "file_get_contents ",
    "abs ",
    "pow ",
    "sin ",
    "cos ",
    "tan ",
    "__construct ",
    "__destruct ",
    "stdClass ",
    "Exception ",
    "ErrorException ",
    "Error ",
    "ParseError ",
    "TypeError ",
    "ArithmeticError ",
    "DivisionByZeroError ",
    "Closure ",
    "Generator ",
    "ClosedGeneratorException ",
    "DateTime ",
    "DateTimeImmutable ",
    "DateTimeZone ",
    "DateInterval ",
    "DatePeriod ",
    "LibXMLError ",
    "DOMException ",
    "DOMStringList ",
    "DOMNameList ",
    "DOMImplementationList ",
    "DOMImplementationSource ",
    "DOMImplementation ",
    "DOMNode ",
    "DOMNameSpaceNode ",
    "DOMDocumentFragment ",
    "DOMDocument ",
    "DOMNodeList ",
    "DOMNamedNodeMap ",
    "DOMCharacterData ",
    "DOMAttr ",
    "DOMElement ",
    "DOMText ",
    "DOMComment ",
    "DOMTypeinfo ",
    "DOMUserDataHandler ",
    "DOMDomError ",
    "DOMErrorHandler ",
    "DOMLocator ",
    "DOMConfiguration ",
    "DOMCdataSection ",
    "DOMDocumentType ",
    "DOMNotation ",
    "DOMEntity ",
    "DOMEntityReference ",
    "DOMProcessingInstruction ",
    "DOMStringExtend ",
    "DOMXPath ",
    "finfo ",
    "LogicException ",
    "BadFunctionCallException ",
    "BadMethodCallException ",
    "DomainException ",
    "InvalidArgumentException ",
    "LengthException ",
    "OutOfRangeException ",
    "RuntimeException ",
    "OutOfBoundsException ",
    "OverflowException ",
    "RangeException ",
    "UnderflowException ",
    "UnexpectedValueException ",
    "RecursiveIteratorIterator ",
    "IteratorIterator ",
    "FilterIterator ",
    "RecursiveFilterIterator ",
    "CallbackFilterIterator ",
    "RecursiveCallbackFilterIterator ",
    "ParentIterator ",
    "LimitIterator ",
    "CachingIterator ",
    "RecursiveCachingIterator ",
    "NoRewindIterator ",
    "AppendIterator ",
    "InfiniteIterator ",
    "RegexIterator ",
    "RecursiveRegexIterator ",
    "EmptyIterator ",
    "RecursiveTreeIterator ",
    "ArrayObject ",
    "ArrayIterator ",
    "RecursiveArrayIterator ",
    "SplFileInfo ",
    "DirectoryIterator ",
    "FilesystemIterator ",
    "RecursiveDirectoryIterator ",
    "GlobIterator ",
    "SplFileObject ",
    "SplTempFileObject ",
    "SplDoublyLinkedList ",
    "SplQueue ",
    "SplStack ",
    "SplHeap ",
    "SplMinHeap ",
    "SplMaxHeap ",
    "SplPriorityQueue ",
    "SplFixedArray ",
    "SplObjectStorage ",
    "MultipleIterator ",
    "PDOException ",
    "PDO ",
    "PDOStatement ",
    "PDORow ",
    "SessionHandler ",
    "ReflectionException ",
    "Reflection ",
    "ReflectionFunctionAbstract ",
    "ReflectionFunction ",
    "ReflectionGenerator ",
    "ReflectionParameter ",
    "ReflectionType ",
    "ReflectionMethod ",
    "ReflectionClass ",
    "ReflectionObject ",
    "ReflectionProperty ",
    "ReflectionExtension ",
    "ReflectionZendExtension ",
    "__PHP_Incomplete_Class ",
    "php_user_filter ",
    "Directory ",
    "AssertionError ",
    "SimpleXMLElement ",
    "SimpleXMLIterator ",
    "PharException ",
    "Phar ",
    "PharData ",
    "PharFileInfo ",
    "XMLReader ",
    "XMLWriter ",
    "CURLFile ",
    "ZipArchive ",
);

$r_encaps_strings = array(
	"\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"",
	"\"\\x00\\x01\\x02\\x03\\x04\\x05\\x06\\x07\\x08\\x09\\x0a\\x0b\\x0c\\x0d\\x0e\\x0f\\x10\\x11\\x12\\x13\\x14\\x15\\x16\\x17\\x18\\x19\\x1a\\x1b\\x1c\\x1d\\x1e\\x1f\\x20\\x21\\x22\\x23\\x24\\x25\\x26\\x27\\x28\\x29\\x2a\\x2b\\x2c\\x2d\\x2e\\x2f\\x30\\x31\\x32\\x33\\x34\\x35\\x36\\x37\\x38\\x39\\x3a\\x3b\\x3c\\x3d\\x3e\\x3f\\x40\\x41\\x42\\x43\\x44\\x45\\x46\\x47\\x48\\x49\\x4a\\x4b\\x4c\\x4d\\x4e\\x4f\\x50\\x51\\x52\\x53\\x54\\x55\\x56\\x57\\x58\\x59\\x5a\\x5b\\x5c\\x5d\\x5e\\x5f\\x60\\x61\\x62\\x63\\x64\\x65\\x66\\x67\\x68\\x69\\x6a\\x6b\\x6c\\x6d\\x6e\\x6f\\x70\\x71\\x72\\x73\\x74\\x75\\x76\\x77\\x78\\x79\\x7a\\x7b\\x7c\\x7d\\x7e\\x7f\\x80\\x81\\x82\\x83\\x84\\x85\\x86\\x87\\x88\\x89\\x8a\\x8b\\x8c\\x8d\\x8e\\x8f\\x90\\x91\\x92\\x93\\x94\\x95\\x96\\x97\\x98\\x99\\x9a\\x9b\\x9c\\x9d\\x9e\\x9f\\xa0\\xa1\\xa2\\xa3\\xa4\\xa5\\xa6\\xa7\\xa8\\xa9\\xaa\\xab\\xac\\xad\\xae\\xaf\\xb0\\xb1\\xb2\\xb3\\xb4\\xb5\\xb6\\xb7\\xb8\\xb9\\xba\\xbb\\xbc\\xbd\\xbe\\xbf\\xc0\\xc1\\xc2\\xc3\\xc4\\xc5\\xc6\\xc7\\xc8\\xc9\\xca\\xcb\\xcc\\xcd\\xce\\xcf\\xd0\\xd1\\xd2\\xd3\\xd4\\xd5\\xd6\\xd7\\xd8\\xd9\\xda\\xdb\\xdc\\xdd\\xde\\xdf\\xe0\\xe1\\xe2\\xe3\\xe4\\xe5\\xe6\\xe7\\xe8\\xe9\\xea\\xeb\\xec\\xed\\xee\\xef\\xf0\\xf1\\xf2\\xf3\\xf4\\xf5\\xf6\\xf7\\xf8\\xf9\\xfa\\xfb\\xfc\\xfd\\xfe\\xff\"",
	"\"%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n\"",
	"\"encapsstring1\"",
	"\"encapsstring2\"",
	"\"encapsstring3\"",
	"\"encapsstring4\"",
	"\"encapsstring5\"",
);

$r_variables = array(
	"\$variable1",
	"\$variable2",
	"\$variable3",
	"\$variable4",
	"\$variable5",
	"\$_GLOBALS",
	"\$_SERVER",
	"\$_REQUEST",
	"\$_ENV",
	"\$_GET",
	"\$_POST",
	"\$_FILES",
	"\$_SESSION",
	"\$_COOKIE",
	"\$argv",
	"\$argc",
);

$r_whitespace = array(
	" ",
	"\t",
	"\r",
	"\n",
);

$r_tabs_and_spaces = array(
	" ",
	"\t",
);

//$r_tokens = ??

$r_any_char = array_merge(
	range("A", "Z"),
	range("a", "z")
);

$r_newline = array(
	"\n"
);


/*
$interesting_bools = array(
	true,
	false,
);

$interesting_resources = array(
	fopen("/dev/null", "r+"),
);

$interesting_callables = array(
	function(){ gc_collect_cycles(); },
	function(){ flush(); },
);

*/